services:
  db:
    image: mysql:8.0
    container_name: danylo_todo_mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: danylo_todo
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: danylo
      MYSQL_PASSWORD: danylo
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
